namespace: production
appLabel: laravel

# Image settings for PHP app
image:
  repository: asadanas/admin-app
  tag: latest
  pullPolicy: Always

# Nginx settings
nginx:
  replicas: 2
  image:
    repository: asadanas/admin-nginx
    tag: latest
    pullPolicy: Always
  resources:
    limits:
      cpu: "1"
      memory: 1Gi
    requests:
      cpu: 500m
      memory: 512Mi

# App settings
app:
  replicas: 2
  resources:
    limits:
      cpu: "1"
      memory: 1Gi
    requests:
      cpu: 500m
      memory: 512Mi

# Database
db:
  port: "3306"
  database: "laravel"
  username: "root"

# Redis
redis:
  image: redis:7-alpine
  persistence:
    enabled: true
    size: 5Gi
    storageClass: nfs-csi

# Ingress
domain: spa.getnatai.com
ingressClassName: nginx

# Environment variables
env:
  APP_NAME: "Laravel Vue Spa"
  APP_ENV: "production"
  APP_DEBUG: "false"
  APP_URL: "http://localhost"
  DB_CONNECTION: "mysql"
  LOG_CHANNEL: "stack"
  BROADCAST_DRIVER: "log"
  CACHE_DRIVER: "redis"
  QUEUE_CONNECTION: "redis"
  SESSION_DRIVER: "redis"
  SESSION_LIFETIME: "120"
  JWT_TTL: "1440"
  
  # Mail
  MAIL_MAILER: "smtp"
  MAIL_HOST: "smtp.mailtrap.io"
  MAIL_PORT: "2525"
  MAIL_ENCRYPTION: "null"
  MAIL_FROM_ADDRESS: "null"
  MAIL_FROM_NAME: "${APP_NAME}"

