apiVersion: batch/v1
kind: Job
metadata:
  name: laravel-migration
  namespace: production
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: migration
        image: asadanas/laravel-vue-spa-2026-app:latest
        envFrom:
        - configMapRef:
            name: laravel-config
        - secretRef:
            name: laravel-secrets
        - secretRef:
            name: db-credentials
        env:
        - name: DB_HOST
          value: "45.125.222.194"
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: password
        - name: CACHE_DRIVER
          value: "file"  # Redis extension na thakle file use koro
        - name: SESSION_DRIVER
          value: "file"
        - name: QUEUE_CONNECTION
          value: "sync"
        command:
        - php
        - artisan
        - migrate
        - --force
