apiVersion: v1
kind: Secret
metadata:
  name: laravel-secrets
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "laravel-vue-app.labels" . | nindent 4 }}
  annotations:
    helm.sh/resource-policy: keep
type: Opaque
data:
  APP_KEY: {{ .Values.secrets.APP_KEY }}
  JWT_SECRET: {{ .Values.secrets.JWT_SECRET }}
  REDIS_PASSWORD: {{ "null" | b64enc }}
