apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "laravel-vue-app.labels" . | nindent 4 }}
type: Opaque
data:
  username: {{ .Values.db.username | b64enc }}
  password: {{ .Values.db.password | b64enc }}
