{{- if .Values.secrets.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "laravel-vue-app.fullname" . }}-secrets
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "laravel-vue-app.labels" . | nindent 4 }}
  annotations:
    helm.sh/resource-policy: keep  # ← Prevent accidental deletion on helm upgrade
type: Opaque
stringData:
  # Application
  APP_KEY: {{ .Values.secrets.appKey | quote }}
  JWT_SECRET: {{ .Values.secrets.jwtSecret | quote }}
  
  # Database
  DB_HOST: {{ .Values.secrets.dbHost | quote }}
  DB_PORT: {{ .Values.secrets.dbPort | quote }}
  DB_USERNAME: {{ .Values.secrets.dbUsername | quote }}
  DB_PASSWORD: {{ .Values.secrets.dbPassword | quote }}
{{- end }}
