apiVersion: v1
kind: Service
metadata:
  name: app
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "laravel-vue-app.labels" . | nindent 4 }}
    app: web
spec:
  type: {{ .Values.service.type }}
  selector:
    app: web
    {{- include "laravel-vue-app.selectorLabels" . | nindent 4 }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 9000

---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "laravel-vue-app.fullname" . }}-nginx
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "laravel-vue-app.labels" . | nindent 4 }}
    app: nginx
spec:
  type: {{ .Values.service.type }}
  selector:
    app: nginx
    {{- include "laravel-vue-app.selectorLabels" . | nindent 4 }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
